title: Knowledge Sharing
description: A Simple Blog by redqx
author: Den9Qux1ang
github: https://github.com/redqx
about:  "你的对手是\n神圣兽国\n游尾郡窝窝乡\n独行族妖侠\n蛮吉"
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    - icon: fa-twitter
      link: "https://x.com/smilere441915"
    # - icon: fa-linkedin
    #   link: "https://www.linkedin.com/in/eduardo-novella-3b808260/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/redqx"

share:
  twitter_username: resmilere441915
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://redqx.github.io"
baseurl: "https://redqx.github.io"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
